

with smoking_md as (

select 
CAST(lssb.HUB_SITE_PATIENT_SK AS STRING) AS PATIENT_NUMBER,
CAST(hssb.SITE_ID AS STRING) AS SITE_ID,
cast("MD" as STRING) AS SOURCE_SYSTEM,
cast('SAT_SITE_PATIENT_CLINICAL_MD_OMOP' as STRING) as SOURCE_TABLE,
NULL AS PROVIDER_ID,
cast(hssb.RECORD_ID AS STRING) as RECORD_ID,
cast(NULL as STRING) as RECORD_STATUS,
cast(case 
		when sssb.smoker = 'N' or sssb.smoker = 'n'
		then 1
		when sssb.smoker = 'X'
		then 2
		when sssb.smoker = 'Y'
		then 3
		ELSE
		0
		END as int) as SMOKING_STATUS_CODE,
cast(case 
		when sssb.smoker = 'N' or sssb.smoker = 'n'
		then 'Non-Smoker'
		when sssb.smoker = 'X'
		then 'Ex-Smoker'
		when sssb.smoker = 'Y'
		then 'Smoker'
		ELSE
		'Not Recorded'
		END as STRING) as SMOKING_STATUS_NAME,
cast(null as int) AS PAST_SMOKING_CODE,
cast(null as int) as SMOKING_PRODUCT_TYPE,
cast(sssb.STARTED_SMOKING as STRING) as SMOKING_START_DATE,
cast(null as INT) as PAST_SMOKING_START_DATE,
cast(sssb.SMOKING_FREQUENCY as STRING) as SMOKING_FREQUENCY,
cast(sssb.SMOKES_PER_DAY as int) as SMOKES_PER_DAY,
cast(sssb.ceased_smoking as STRING) as SMOKING_CEASED_DATE,
cast(null as INT) as PAST_SMOKING_STOPPED_DATE,
cast(sssb.SMOKING_ASSESSMENT_DATE as STRING) AS SMOKING_ASSESSMENT_DATE, 
cast(sssb.smoking_stage_change_assessment AS STRING) as SMOKING_CHANGE_STAGE_ASSESSMENT,
cast(sssb.SMOKING_LAST_QUIT_ATTEMPT_DATE as STRING) AS SMOKING_LAST_QUIT_ATTEMPT_DATE, 
cast(sssb.SMOKING_LONGEST_ABSTINENCE_DURATION as STRING) as SMOKING_LONGEST_ABSTINENCE_DURATION,
cast(sssb.SMOKING_ABSTINENCE_UNIT as STRING) as SMOKING_ABSTINENCE_UNIT , 
cast(sssb.SMOKING_COMMENT as STRING) as SMOKING_COMMENT, 
cast(sssb.created_datetime as timestamp) as CREATED_DATETIME,
cast(sssb.updated_datetime as timestamp) as UPDATED_DATETIME,
CAST(sssb.OMD_EFFECTIVE_DATETIME AS TIMESTAMP) AS OMD_EFFECTIVE_DATETIME,
CAST(sssb.OMD_SOURCE_ROW_ID AS INT) AS OMD_SOURCE_ROW_ID,
CAST(sssb.OMD_INSERT_MODULE_INSTANCE_ID AS INT) AS OMD_INSERT_MODULE_INSTANCE_ID,
CAST(sssb.OMD_EXPIRY_DATETIME AS TIMESTAMP) AS OMD_EXPIRY_DATETIME,
CAST(sssb.OMD_CURRENT_RECORD_INDICATOR AS STRING) AS OMD_CURRENT_RECORD_INDICATOR,
CAST(sssb.OMD_DELETED_RECORD_INDICATOR AS STRING) AS OMD_DELETED_RECORD_INDICATOR,
CAST(sssb.OMD_RECORD_SOURCE_ID AS INT) AS OMD_RECORD_SOURCE_ID,
CAST(sssb.OMD_HASH_FULL_RECORD AS STRING) AS OMD_HASH_FULL_RECORD 
from `nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`HUB_SITE_PATIENT_CLINICAL_MD_OMOP` hssb
inner join 
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_SITE_PATIENT_CLINICAL_MD_OMOP` sssb
on hssb.HUB_SITE_PATIENT_CLINICAL_MD_SK = sssb.HUB_SITE_PATIENT_CLINICAL_MD_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LNK_SITE_PATIENT_CLINICAL_MD_OMOP` lssb
on hssb.HUB_SITE_PATIENT_CLINICAL_MD_SK = lssb.HUB_SITE_PATIENT_CLINICAL_MD_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LSAT_SITE_PATIENT_CLINICAL_MD_OMOP` lsssb
on lssb.LNK_SITE_PATIENT_CLINICAL_MD_SK = lsssb.LNK_SITE_PATIENT_CLINICAL_MD_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`HUB_SITE_PATIENT_OMOP` hsp
ON lssb.HUB_SITE_PATIENT_SK = hsp.HUB_SITE_PATIENT_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_SITE_PATIENT_MD_OMOP` ssp
ON hsp.HUB_SITE_PATIENT_SK = ssp.HUB_SITE_PATIENT_SK
WHERE
	sssb.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND sssb.OMD_DELETED_RECORD_INDICATOR = 'N'
	AND lsssb.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND lsssb.OMD_DELETED_RECORD_INDICATOR = 'N'
	AND ssp.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND ssp.OMD_DELETED_RECORD_INDICATOR = 'N'

)

select * from smoking_md