

with sitebdv as (
select SITE_NAME, HUB_SITE_SK ,SITE_IDENTIFIER, STATE, POSTCODE_ORIGINAL, POSTCODE_OVERRIDE,
POSTCODE_OVERRIDE_FLAG, POSTCODE_OVERRIDE_REASON, SOURCE_SYSTEM, 
MAX(CAST(CRM_SITE_RECRUITMENT_AGREED_SIGNED_DATE AS TIMESTAMP)) AS CRM_SITE_RECRUITMENT_AGREED_SIGNED_DATE, 
CRM_SITE_RECRUITMENT_STATUS, 
MAX(CAST(CRM_SITE_RECRUITMENT_WITHDRAWN_DATE AS TIMESTAMP)) AS CRM_SITE_RECRUITMENT_WITHDRAWN_DATE, 
SITE_EXTRACTION_TYPE, 
MAX(CAST(SITE_DWH_BASELINE_DATE AS TIMESTAMP)) AS SITE_DWH_BASELINE_DATE, 
MAX(CAST(SITE_LATEST_LOAD_DATE AS TIMESTAMP)) AS SITE_LATEST_LOAD_DATE
from
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_BDV_SITE_OMOP`
WHERE SOURCE_SYSTEM not like 'Unknown' and CRM_SITE_RECRUITMENT_STATUS like 'Participating'
GROUP BY SITE_NAME, HUB_SITE_SK ,SITE_IDENTIFIER, STATE, POSTCODE_ORIGINAL, POSTCODE_OVERRIDE,
POSTCODE_OVERRIDE_FLAG, POSTCODE_OVERRIDE_REASON, SOURCE_SYSTEM,
CRM_SITE_RECRUITMENT_STATUS, SITE_EXTRACTION_TYPE
),

site_table as (
select
cast(hso.HUB_SITE_SK as string) as SITE_NUMBER,
cast(hso.SITE_ID as string) as SITE_ID,
cast(sbdv.SITE_NAME as string) as SITE_NAME,
cast(satt.SITE_CONTROLLER as string) as SITE_CONTROLLER,
cast(satt.SITE_ADDRESS as string) as SITE_ADDRESS,
cast(satt.SITE_EMAIL as string) as SITE_EMAIL,
cast(satt.SITE_PHONE as string) as SITE_PHONE,
cast(satt.SITE_DATAPROCESSING_ENABLED as int) as SITE_DATAPROCESSING_ENABLED,
cast(satt.SITE_REQUEST_EXPORTLOGS as int) as SITE_REQUEST_EXPORTLOGS,
cast(satt.SITE_REQUEST_DATARESET as int) as SITE_REQUEST_DATARESET,
cast(satt.SITE_WEBSERVICE_ENABLED as int) as SITE_WEBSERVICE_ENABLED,
cast(satt.SITE_WEBSITE_ENABLED as int) as SITE_WEBSITE_ENABLED,
cast(satt.SITE_CREATED as timestamp) as SITE_CREATED_DATE,
cast(satt.SITE_MODIFIED as timestamp) as SITE_MODIFIED_DATE,
cast(null as string) as OMD_CDC_OPERATION,
cast(null as string) as MULTI_PRACTICE_FLAG,
cast(sbdv.SITE_IDENTIFIER as string) as SITE_IDENTIFIER,
cast(sbdv.STATE as string) as STATE,
cast(sbdv.POSTCODE_ORIGINAL as string) as POSTCODE_ORIGINAL,
cast(sbdv.POSTCODE_OVERRIDE as string) as POSTCODE_OVERRIDE,
cast(sbdv.POSTCODE_OVERRIDE_FLAG as int) as POSTCODE_OVERRIDE_FLAG,
cast(sbdv.POSTCODE_OVERRIDE_REASON as string) as POSTCODE_OVERRIDE_REASON,
cast(sbdv.SOURCE_SYSTEM as string) as SOURCE_SYSTEM,
cast(sbdv.CRM_SITE_RECRUITMENT_AGREED_SIGNED_DATE as timestamp) as CRM_SITE_RECRUITMENT_AGREED_SIGNED_DATE,
cast(sbdv.CRM_SITE_RECRUITMENT_STATUS as string) as CRM_SITE_RECRUITMENT_STATUS,
cast(sbdv.CRM_SITE_RECRUITMENT_WITHDRAWN_DATE as timestamp) as CRM_SITE_RECRUITMENT_WITHDRAWN_DATE,
cast(sbdv.SITE_EXTRACTION_TYPE as string) as SITE_EXTRACTION_TYPE,
cast(sbdv.SITE_DWH_BASELINE_DATE as timestamp) as SITE_DWH_BASELINE_DATE,
cast(sbdv.SITE_LATEST_LOAD_DATE as timestamp) as SITE_LATEST_LOAD_DATE
from 
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`HUB_SITE_OMOP` hso 
LEFT JOIN 
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_SITE_GRH_OMOP` satt
ON hso.HUB_SITE_SK = satt.HUB_SITE_SK
LEFT JOIN 
sitebdv sbdv
ON hso.HUB_SITE_SK = sbdv.HUB_SITE_SK
)
select DISTINCT * from site_table