

with pathology_lipids as (
select
cast(lbpa.HUB_SITE_PATIENT_SK as STRING) as PATIENT_NUMBER,
cast(hbpo.SITE_ID as STRING) as SITE_ID,
cast(hbpo.PATHOLOGY_ID AS STRING) as PATHOLOGY_ID,
cast(sbpl.PATHOLOGY_TEST_DATETIME as TIMESTAMP) AS PATHOLOGY_TEST_DATETIME,
cast(sbpl.PATHOLOGY_TEST_TYPE as STRING) AS PATHOLOGY_TEST_TYPE,
cast(sbpl.LOINC_CODE as STRING) AS LOINC_CODE,
cast(sbpl.LOINC_CODE_VALID_INDICATOR as STRING) AS LOINC_CODE_VALID_INDICATOR,
cast(sbpl.RESULT_VALUE_CIS as STRING) AS RESULT_VALUE_CIS,
cast(sbpl.RESULT_VALUE_STND as STRING) AS RESULT_VALUE_STND,
cast(sbpl.RESULT_VALUE_TYPE as STRING) AS RESULT_VALUE_TYPE,
cast(sbpl.DETECTED_CIS_UNIT_OF_MEASURE as STRING) AS DETECTED_CIS_UNIT_OF_MEASURE,
cast(sbpl.RESULT_AVAILABLE_INDICATOR as STRING) AS RESULT_AVAILABLE_INDICATOR,
cast(sbpl.RESULT_VALID_RANGE_INDICATOR as STRING) AS RESULT_VALID_RANGE_INDICATOR,
cast(sbpl.RESULT_VALID_FORMAT_INDICATOR as STRING) AS RESULT_VALID_FORMAT_INDICATOR,
cast(sbpl.RESULT_INVALID_REASON as STRING) AS RESULT_INVALID_REASON,
cast(sbpl.RESULT_IMPORT_INDICATOR as STRING) AS RESULT_IMPORT_INDICATOR,
cast(sbpl.RESULT_HEADER_ONLY_INDICATOR as STRING) AS RESULT_HEADER_ONLY_INDICATOR,
cast(sbpl.RESULT_TRANSMISSION_TYPE as STRING) AS RESULT_TRANSMISSION_TYPE,
cast('<4.0mmol/L' as STRING) AS LIPIDS_TOTAL_CHOLESTEROL_RESULT_VALUE_RANGE,
cast('>1.0mmol/L' as STRING) AS LIPIDS_HDL_RESULT_VALUE_RANGE,
cast('<2.0mmol/L' as STRING) AS LIPIDS_LDL_RESULT_VALUE_RANGE,
cast('<2.0mmol/L' as STRING) AS LIPIDS_TRIGLYCERIDES_RESULT_VALUE_RANGE,
cast('BDV' as string) as SOURCE_SYSTEM,
cast('SAT_BDV_PATHOLOGY_LIPIDS_OMOP' as string) as SOURCE_TABLE
from 
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`HUB_BDV_PATHOLOGY_OMOP` hbpo
inner join 
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_BDV_PATHOLOGY_LIPIDS_OMOP` sbpl
on hbpo.HUB_BDV_PATHOLOGY_SK = sbpl.HUB_BDV_PATHOLOGY_SK
inner join 
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LNK_BDV_PATHOLOGY_OMOP` lbpa
on hbpo.HUB_BDV_PATHOLOGY_SK = lbpa.HUB_BDV_PATHOLOGY_SK
inner join 
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LSAT_BDV_PATHOLOGY_OMOP` lsbpa
on lbpa.LNK_BDV_PATHOLOGY_SK = lsbpa.LNK_BDV_PATHOLOGY_SK
WHERE 
	sbpl.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND sbpl.OMD_DELETED_RECORD_INDICATOR = 'N'
    AND lsbpa.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND lsbpa.OMD_DELETED_RECORD_INDICATOR = 'N'
)

select * from pathology_lipids