
with billing_service_phc_bp as (
select
CAST(lbdvbs.HUB_SITE_PATIENT_SK AS STRING) AS PATIENT_NUMBER,
CAST(hbs.SITE_ID AS STRING) AS SITE_ID, 
CAST(hbs.SOURCE_SYSTEM AS STRING) AS SOURCE_SYSTEM , 
'SAT_BILLING_SERVICE_PHC_BP_OMOP' AS SOURCE_TABLE, 
CAST(NULL AS STRING) AS PROVIDER_ID, 
CAST(hbs.BILLING_SERVICE_ID AS STRING) as SERVICE_ID,
CAST(sbdvbs.BILLING_SERVICE_DATE AS TIMESTAMP) AS SERVICE_DATETIME,
CAST(sbspb.MBS_ITEM AS STRING) as ITEM_NUMBER,
CAST(sbspb.PATIENTS AS INT) AS SERVICE_PATIENT_COUNT,
CAST(sbspb.RECORD_STATUS AS STRING) as SERVICE_RECORD_STATUS,
CAST(sbdvbs.BILLING_SERVICE_VISIT_DATE AS TIMESTAMP) as VISIT_DATETIME,
CAST(sbspb.CREATED AS TIMESTAMP) AS CREATED_DATETIME,
CAST(sbspb.UPDATED AS TIMESTAMP) AS UPDATED_DATETIME,
CAST(sbspb.OMD_EFFECTIVE_DATETIME AS TIMESTAMP) AS OMD_EFFECTIVE_DATETIME,
CAST(sbspb.OMD_SOURCE_ROW_ID AS INT) AS OMD_SOURCE_ROW_ID,
CAST(sbspb.OMD_INSERT_MODULE_INSTANCE_ID AS INT) AS OMD_INSERT_MODULE_INSTANCE_ID,
CAST(sbspb.OMD_EXPIRY_DATETIME AS TIMESTAMP) AS OMD_EXPIRY_DATETIME,
CAST(sbspb.OMD_CURRENT_RECORD_INDICATOR AS STRING) AS OMD_CURRENT_RECORD_INDICATOR,
CAST(sbspb.OMD_DELETED_RECORD_INDICATOR AS STRING) AS OMD_DELETED_RECORD_INDICATOR,
CAST(sbspb.OMD_RECORD_SOURCE_ID AS INT) AS OMD_RECORD_SOURCE_ID,
CAST(sbspb.OMD_HASH_FULL_RECORD AS STRING) AS OMD_HASH_FULL_RECORD
from 
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`HUB_BILLING_SERVICE_OMOP` hbs
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_BILLING_SERVICE_PHC_BP_OMOP` sbspb
on hbs.HUB_BILLING_SERVICE_SK = sbspb.HUB_BILLING_SERVICE_SK
inner join 
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_BDV_BILLING_SERVICE_OMOP` sbdvbs
on hbs.HUB_BILLING_SERVICE_SK = sbdvbs.HUB_BILLING_SERVICE_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LNK_BDV_BILLING_SERVICE_OMOP` lbdvbs
on hbs.HUB_BILLING_SERVICE_SK = lbdvbs.HUB_BILLING_SERVICE_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LSAT_BDV_BILLING_SERVICE_OMOP` lsbdvbs
ON lbdvbs.LNK_BDV_BILLING_SERVICE_SK = lsbdvbs.LNK_BDV_BILLING_SERVICE_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`HUB_SITE_PATIENT_OMOP` hsp
ON lbdvbs.HUB_SITE_PATIENT_SK = hsp.HUB_SITE_PATIENT_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_SITE_PATIENT_PHC_BP_OMOP` ssp
ON hsp.HUB_SITE_PATIENT_SK = ssp.HUB_SITE_PATIENT_SK
WHERE
	sbspb.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND sbspb.OMD_DELETED_RECORD_INDICATOR = 'N'
    AND sbdvbs.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND sbdvbs.OMD_DELETED_RECORD_INDICATOR = 'N'
    AND lsbdvbs.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND lsbdvbs.OMD_DELETED_RECORD_INDICATOR = 'N'
    AND ssp.OMD_CURRENT_RECORD_INDICATOR = 'Y'
    AND ssp.OMD_DELETED_RECORD_INDICATOR = 'N'
)

select * from billing_service_phc_bp