

with encounter_reason_md as (
select 
cast(leo.HUB_SITE_PATIENT_SK AS STRING) AS PATIENT_NUMBER,
cast(heo.SITE_ID AS STRING) AS SITE_ID,
NULL as PROVIDER_ID,
cast(heo.SOURCE_SYSTEM AS STRING) AS SOURCE_SYSTEM,
cast('SAT_ENCOUNTR_MD_EXCLD_SENSITIVE_DATA_OMOP' as STRING) AS SOURCE_TABLE,
cast(heo.ENCOUNTER_ID AS STRING) AS ENCOUNTER_ID,
cast(sem.VISIT_DATE AS TIMESTAMP) AS VISIT_DATETIME,
cast(sem.REASON as STRING) AS ENCOUNTER_REASON,
cast(setm.ENCOUNTER_TYPE AS STRING) AS ENCOUNTER_TYPE,
cast(sem.REASON_CODE as STRING) AS ENCOUNTER_REASON_CODE,
cast(sem.CREATED_DATETIME as TIMESTAMP) AS CREATED_DATETIME,
cast(sem.UPDATED_DATETIME AS TIMESTAMP) AS UPDATED_DATETIME,
CAST(sem.OMD_EFFECTIVE_DATETIME AS TIMESTAMP) AS OMD_EFFECTIVE_DATETIME,
CAST(sem.OMD_SOURCE_ROW_ID AS INT) AS OMD_SOURCE_ROW_ID,
CAST(sem.OMD_INSERT_MODULE_INSTANCE_ID AS INT) AS OMD_INSERT_MODULE_INSTANCE_ID,
CAST(sem.OMD_EXPIRY_DATETIME AS TIMESTAMP) AS OMD_EXPIRY_DATETIME,
CAST(sem.OMD_CURRENT_RECORD_INDICATOR AS STRING) AS OMD_CURRENT_RECORD_INDICATOR,
CAST(sem.OMD_DELETED_RECORD_INDICATOR AS STRING) AS OMD_DELETED_RECORD_INDICATOR,
CAST(sem.OMD_RECORD_SOURCE_ID AS INT) AS OMD_RECORD_SOURCE_ID,
CAST(sem.OMD_HASH_FULL_RECORD AS STRING) AS OMD_HASH_FULL_RECORD
from
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`HUB_ENCOUNTER_OMOP` heo
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_ENCOUNTR_MD_EXCLD_SENSITIVE_DATA_OMOP` sem
on heo.HUB_ENCOUNTER_SK = sem.HUB_ENCOUNTER_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_ENCOUNTER_TYPE_MD_OMOP` setm 
on heo.HUB_ENCOUNTER_SK = setm.HUB_ENCOUNTER_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LNK_ENCOUNTER_OMOP` leo
on sem.HUB_ENCOUNTER_SK = leo.HUB_ENCOUNTER_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LSAT_ENCOUNTER_OMOP` lseo
on leo.LNK_ENCOUNTER_SK = lseo.LNK_ENCOUNTER_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LNK_ENCOUNTER_TYPE_MD_OMOP` letm 
on setm.HUB_ENCOUNTER_SK = letm.HUB_ENCOUNTER_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LSAT_ENCOUNTER_TYPE_MD_OMOP` lset
on letm.LNK_ENCOUNTER_TYPE_MD_SK = lset.LNK_ENCOUNTER_TYPE_MD_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`HUB_SITE_PATIENT_OMOP` hsp
ON leo.HUB_SITE_PATIENT_SK = hsp.HUB_SITE_PATIENT_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_SITE_PATIENT_MD_OMOP` ssp
ON hsp.HUB_SITE_PATIENT_SK = ssp.HUB_SITE_PATIENT_SK
WHERE
	setm.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND setm.OMD_DELETED_RECORD_INDICATOR = 'N'
    AND sem.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND sem.OMD_DELETED_RECORD_INDICATOR = 'N'
    AND lseo.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND lseo.OMD_DELETED_RECORD_INDICATOR = 'N'
    AND lset.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND lset.OMD_DELETED_RECORD_INDICATOR = 'N'
    AND ssp.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND ssp.OMD_DELETED_RECORD_INDICATOR = 'N'
)


select * from encounter_reason_md