SELECT
    LNK_BDV.HUB_SITE_PATIENT_SK AS PATIENT_NUMBER,
    SAT_BDV.OMD_NPS_SITE_ID AS SITE_ID,
    SAT_BDV.DIAGNOSIS_ID AS DIAGNOSIS_ID,
    SAT_BDV.SOURCE_SYSTEM AS SOURCE_SYSTEM,
    'SAT_BDV_DIAGNOSIS_EXCLD_SENSITIVE_DATA_OMOP' AS SOURCE_TABLE,
    SAT_BDV.DIAGNOSIS_TYPE AS DIAGNOSIS_TYPE,
    SAT_BDV.DIAGNOSIS_NAME AS DIAGNOSIS_REASON,
    SAT_BDV.DIAGNOSIS_CODE AS DIAGNOSIS_REASON_CODE,
    CAST(SAT_BDV.DIAGNOSIS_DATE AS STRING) AS DIAGNOSIS_DATE,
    SAT_BDV.CIS_CODED_STATUS AS CIS_CODED_STATUS,
    SAT_BDV.DIAGNOSIS_STATUS_ACTIVE_FLAG AS DIAGNOSIS_STATUS_ACTIVE_FLAG,
    SAT_BDV.CONFIDENTIAL_FLAG AS CONFIDENTIAL_FLAG,
    SAT_BDV.SUMMARY_FLAG AS SUMMARY_FLAG,
    SAT_BDV.DIFFERENTIAL_FLAG AS DIFFERENTIAL_FLAG,
    SAT_BDV.PROVISIONAL_FLAG AS PROVISIONAL_FLAG,
    CAST(SAT_BDV.CIS_CREATED_DATETIME AS TIMESTAMP) AS CREATED_DATETIME,
    CAST(SAT_BDV.CIS_CREATED_DATETIME AS TIMESTAMP) AS UPDATED_DATETIME,
    CAST(SAT_BDV.OMD_EFFECTIVE_DATETIME AS TIMESTAMP) AS OMD_EFFECTIVE_DATETIME,
    SAT_BDV.OMD_SOURCE_ROW_ID AS OMD_SOURCE_ROW_ID,
    SAT_BDV.OMD_INSERT_MODULE_INSTANCE_ID AS OMD_INSERT_MODULE_INSTANCE_ID,
    CAST(SAT_BDV.OMD_EXPIRY_DATETIME AS TIMESTAMP) AS OMD_EXPIRY_DATETIME,
    SAT_BDV.OMD_CURRENT_RECORD_INDICATOR AS OMD_CURRENT_RECORD_INDICATOR,
    SAT_BDV.OMD_DELETED_RECORD_INDICATOR AS OMD_DELETED_RECORD_INDICATOR,
    SAT_BDV.OMD_RECORD_SOURCE_ID AS OMD_RECORD_SOURCE_ID,
    SAT_BDV.OMD_HASH_FULL_RECORD AS OMD_HASH_FULL_RECORD
FROM 
/** BDV table joins **/
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`HUB_BDV_DIAGNOSIS_OMOP` HUB_BDV
JOIN
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LNK_BDV_DIAGNOSIS_OMOP` LNK_BDV
ON
     HUB_BDV.HUB_BDV_DIAGNOSIS_SK = LNK_BDV.HUB_BDV_DIAGNOSIS_SK
JOIN    
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_BDV_DIAGNOSIS_EXCLD_SENSITIVE_DATA_OMOP` SAT_BDV
ON
    LNK_BDV.HUB_BDV_DIAGNOSIS_SK = SAT_BDV.HUB_BDV_DIAGNOSIS_SK
JOIN
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LSAT_BDV_DIAGNOSIS_OMOP` LSAT_BDV
ON
	LNK_BDV.LNK_BDV_DIAGNOSIS_SK = LSAT_BDV.LNK_BDV_DIAGNOSIS_SK
JOIN
/** Patient table joins **/
	`nps-omop-project`.`C_SREDH_NPS_MI_STAGING_SIMPLIFIED_2021_VIEWS_ONLY`.`src_active_patients` ACTIVE_PATIENTS
ON
	LNK_BDV.HUB_SITE_PATIENT_SK = ACTIVE_PATIENTS.HUB_SITE_PATIENT_SK
/* Filters to retrieve non-deleted and current records */
WHERE
	SAT_BDV.OMD_CURRENT_RECORD_INDICATOR = 'Y'
    AND SAT_BDV.OMD_DELETED_RECORD_INDICATOR = 'N'
    AND LSAT_BDV.OMD_CURRENT_RECORD_INDICATOR = 'Y'
    AND LSAT_BDV.OMD_DELETED_RECORD_INDICATOR = 'N'