

with alcohol_bp as (
select
CAST(lasb.HUB_SITE_PATIENT_SK AS STRING) AS PATIENT_NUMBER,
CAST(hasb.SITE_ID AS STRING) AS SITE_ID,
NULL AS PROVIDER_ID,
CAST(hasb.SOURCE_SYSTEM AS STRING) AS SOURCE_SYSTEM,
CAST("SAT_SITE_PATIENT_ALCOHOL_STATUS_BP_OMOP" AS STRING) AS SOURCE_TABLE,
CAST(hasb.RECORD_ID AS STRING) AS RECORD_ID,
CAST(sspasb.RECORD_STATUS AS STRING) AS RECORD_STATUS,
CAST(sspasb.ALCOHOL_CODE AS STRING) AS ALCOHOL_CODE,
CAST(CASE
		WHEN sspasb.ALCOHOL_CODE = 1
		THEN 'Nil'
		WHEN sspasb.ALCOHOL_CODE = 2
		THEN 'Ocassional'
		WHEN sspasb.ALCOHOL_CODE = 3
		THEN 'Moderate'
		WHEN sspasb.ALCOHOL_CODE = 4
		THEN 'Heavy'
		ELSE
		null
		END AS STRING) AS ALCOHOL_STATUS_NAME,
CAST(sspasb.PAST_ALCOHOL_LEVEL as STRING) AS PAST_ALCOHOL_CODE,
CAST(sspasb.DRINKS_PER_DAY AS INT) AS DRINKS_PER_DAY,
CAST(sspasb.DAYS_PER_WEEK AS INT) AS DAYS_PER_WEEK,
CAST(null AS STRING) AS ALCOHOL_ASSESSMENT_DATE,
CAST(sspasb.YEAR_STARTED AS STRING) AS YEAR_STARTED,
CAST(sspasb.YEAR_STOPPED AS STRING) AS YEAR_STOPPED,
CAST(sspasb.PAST_DRINKS_PER_DAY AS STRING) AS PAST_DRINKS_PER_DAY,
CAST(sspasb.PAST_DAYS_PER_WEEK AS STRING) AS PAST_DAYS_PER_WEEK,
CAST(sspasb.CREATED_DATETIME AS TIMESTAMP) AS CREATED_DATETIME, 
CAST(sspasb.UPDATED_DATETIME AS TIMESTAMP) AS UPDATED_DATETIME,
CAST(sspasb.OMD_EFFECTIVE_DATETIME AS TIMESTAMP) AS OMD_EFFECTIVE_DATETIME,
CAST(sspasb.OMD_SOURCE_ROW_ID AS INT) AS OMD_SOURCE_ROW_ID,
CAST(sspasb.OMD_INSERT_MODULE_INSTANCE_ID AS INT) AS OMD_INSERT_MODULE_INSTANCE_ID,
CAST(sspasb.OMD_EXPIRY_DATETIME AS TIMESTAMP) AS OMD_EXPIRY_DATETIME,
CAST(sspasb.OMD_CURRENT_RECORD_INDICATOR AS STRING) AS OMD_CURRENT_RECORD_INDICATOR,
CAST(sspasb.OMD_DELETED_RECORD_INDICATOR AS STRING) AS OMD_DELETED_RECORD_INDICATOR,
CAST(sspasb.OMD_RECORD_SOURCE_ID AS INT) AS OMD_RECORD_SOURCE_ID,
CAST(sspasb.OMD_HASH_FULL_RECORD AS STRING) AS OMD_HASH_FULL_RECORD
from `nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`HUB_SITE_PATIENT_ALCOHOL_STATUS_BP_OMOP` hasb
inner join 
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_SITE_PATIENT_ALCOHOL_STATUS_BP_OMOP` sspasb
on hasb.HUB_SITE_PATIENT_ALCOHOL_STATUS_BP_SK = sspasb.HUB_SITE_PATIENT_ALCOHOL_STATUS_BP_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LNK_SITE_PATIENT_ALCOHOL_STATUS_BP_OMOP` lasb
on hasb.HUB_SITE_PATIENT_ALCOHOL_STATUS_BP_SK = lasb.HUB_SITE_PATIENT_ALCOHOL_STATUS_BP_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`LSAT_SITE_PATIENT_ALCOHOL_STATUS_BP_OMOP` lsasb
on lasb.LNK_SITE_PATIENT_ALCOHOL_STATUS_BP_SK = lsasb.LNK_SITE_PATIENT_ALCOHOL_STATUS_BP_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`HUB_SITE_PATIENT_OMOP` hsp
on lasb.HUB_SITE_PATIENT_SK = hsp.HUB_SITE_PATIENT_SK
inner join
`nps-omop-project`.`B_SREDH_NPS_MI_SF_RDV_BDV_2021`.`SAT_SITE_PATIENT_BP_OMOP` ssp
ON hsp.HUB_SITE_PATIENT_SK = ssp.HUB_SITE_PATIENT_SK
WHERE
	sspasb.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND sspasb.OMD_DELETED_RECORD_INDICATOR = 'N'
	AND lsasb.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND lsasb.OMD_DELETED_RECORD_INDICATOR = 'N'
	AND ssp.OMD_CURRENT_RECORD_INDICATOR = 'Y'
	AND ssp.OMD_DELETED_RECORD_INDICATOR = 'N'
)

SELECT DISTINCT * FROM 
alcohol_bp s1
where OMD_SOURCE_ROW_ID = (SELECT MAX(OMD_SOURCE_ROW_ID) 
FROM alcohol_bp s2
WHERE s1.PATIENT_NUMBER = s2.PATIENT_NUMBER)